# Generated by Django 5.1 on 2024-09-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0002_datasabertas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadosmedico',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'prefiro não dizer')], default='O', max_length=1),
            preserve_default=False,
        ),
    ]
