# Generated by Django 5.1 on 2024-09-14 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico', '0003_dadosmedico_sexo'),
        ('paciente', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='medico.dadosmedico'),
            preserve_default=False,
        ),
    ]
